config/routes.rb
Rails.application.routes.draw do
  resources :menus do
    resources :comments
  end
  get 'home/index'
  get 'home/about'
  get 'home/group'
  get 'home/sapporo'
  get 'home/obihiro'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :menu
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :comments
  default_scope { order(created_at: :desc) }
  
  def self.search(search)
    if search
      Menu.where(['remark LIKE ? or movement LIKE ? or music LIKE ?' , "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      Menu.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
        @comment = Comment.new
    @menu = Menu.find params[:menu_id]
    @menu.comments.create(comment_params)

    redirect_to menu_path(@menu)
  end
  
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  def group
  end
  def sapporo
  end
  def obihiro
  end
  
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    # @menus = Menu.serch
    @menus =  Menu.search(params[:search])
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def search
  #   #Viewのformで取得したパラメータをモデルに渡す
  #   @menus = Menu.search(params[:search])
  #   # raise.params.inspect
  # end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:date, :remark, :movement, :music, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/comments/_comment.html.erb
<div>
  <p>・<%= comment.body %></p>
</div>

app/views/comments/_form.html.erb
<%= form_for [@menu, @menu.comments.build] do |f| %>
  <p>コメントを入力</p>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>
  

app/views/home/about.html.erb
<div class="main">
	
	<h1 class="heading">Capoeira Angolaについて</h1>

	<div class="contents">
		<h2 class="title">Capoeiraとは？</h2>
		<div class="contents-wrapper clearfix">
			<div class="c-image">
				<%= image_tag "pic1.jpg" %>
			</div>
			<div class="c-description">
				<p>　Capoeira（カポエイラ）とは、ブラジル発祥の伝統武道で、格闘技とダンスが合わさったものです。</p>
			</div>
		</div>
	</div>
	
	<div class="contents">
		<h2 class="title">Capoeira Angolaとは？</h2>
		<div class="contents-wrapper clearfix">
			<div class="c-image">
				<%= image_tag "pic2.jpg" %>
			</div>
			<div class="c-description">
				<p>カポエイラには様々な流派があり、中でもAngola（アンゴラ）という流派はより伝統を意識した流派になります。</p>
			</div>
		</div>
	</div>	
	
</div>

<!--サイドスペース-->
<div class="sidemenu">

</div>

app/views/home/group.html.erb
<div class="main">
	
	<h1 class="heading">団体について</h1>
	
	<div class="contents">
		<h2 class="title">Mestre Joao Grande</h2>
		<div class="contents-wrapper clearfix">
			<div class="c-image">
				<%= image_tag("group/MJG.png", width: 200) %>
			</div>
			<div class="c-description">
				<p>私たちのグループのMestre João Grande（メストレ・ジョアングランジ）。1933年1月15日にブラジルのバイーア州 イタギという町で生を受けました。
				彼はカポエィラ・アンゴラ界における伝説のメストレの一人であるMestre pastinha（メストレ・パスチーニャ）の直接の生徒でした。
				カポエイラ・アンゴラに60年以上専念し、世界で尊敬されるメストレの一人です。
				メストレ・ジョアングランジはニューヨークに”Capoeira Angola center”のアカデミアを開き、カポエイラ・アンゴラの歴史と伝統を尊重し、哲学や生き方を教え続けています。
				彼のその教えを受けた人達は国境を越えて世界中に広がっています。
				それらの貢献が認められウプサラ大学から人文博士号を授与されたほか、アメリカ合衆国における伝統芸能の実践者に贈られる最も権威ある米国立芸術基金から人間国宝の称号も受賞しています。
				また、2015年にはブラジル文化勲章を受賞するなど彼の活動は偉大なものとなっています。</p>
			</div>
		</div>
	</div>

	<div class="contents">
		<h2 class="title">Contramestre Denis</h2>
		<div class="contents-wrapper clearfix">
			<div class="c-image">
				<%= image_tag("group/CMD.png", width: 200) %>
			</div>
			<div class="c-description">
				<p>ブラジル　サンパウロ　ジュンディアイ出身の彼は1988年よりカポエイラをスタートさせ、その経験は20年以上になります。
				2013年４月には、メストレ・ジョアングランジに”Capoeira  Angola Center”のグループとして認められ、現在アメリカのイリノイ州シャンペーンのアカデミアにてカポエイラを教えています。
				メストレ・ジョアングランジの生徒として受け入れられた事は、彼にとって大変名誉なことでした。
				2004年以来、アーバナのイリノイ大学のダンス部門で客員講師としてカポエイラのインストラクターをしています。また、同大学で国際カポエイラ会議を主催したUIUCカポエイラクラブの施設顧問でもあります。
				2017年10月にはメストレ・ジョアングランジからContra Mestre(準師範）の資格を授与されました。</p>
			</div>
		</div>
	</div>
</div>


<!--サイドスペース-->
<div class="sidemenu">

</div>

app/views/home/index.html.erb
<!--ビッグイメージ-->
<div class="bigimage">
	<%= image_tag "bigimage.jpg" %>
</div>


<!--メインスペース-->
<div class="main">
	<h1 class="hidden">カポエイラ</h1>
	<div class="features">
		<h2>カポエイラの魅力</h2>
		<div class="section-wrapper clearfix">
			<div class="section">
				<%= image_tag "pic1.jpg" %>
				<h3>心身ともに健康に</h3>
				<p>カポエイラは格闘技とダンスが融合した武道です。その独特な動きの練習はもちろん、歌や楽器の演奏も行います。これらを通じて自身の体と心に向き合い、日常生活で偏りがちな心身のメンテナンスを助けます。</p>
			</div>
			<div class="section">
				<%= image_tag "pic2.jpg" %>
				<h3>コミュニケーション</h3>
				<p>カポエイラの基本は相手との対話。ゲームの中で相手を尊重しながら会話のような掛け合いを楽しみます。またカポエイラという共通言語を通じて様々な仲間と会い、コミュニケーションを広げることができます。</p>
			</div>
			<div class="section">
				<%= image_tag "pic3.jpg" %>
				<h3>伝統・文化・哲学</h3>
				<p>ブラジルの黒人奴隷の反発から生まれたカポエイラを通じて、ブラジルの歴史やポルトガル語、広く社会を学ぶことが出来ます。師の教えを学び、友人や仲間から人生をより楽しく豊かに生きるための考え方を学びます。</p>
			</div>
		</div>
	</div>
	<div class="features">
		<h2 class="title">クラス情報</h2>
		<div class="section-wrapper clearfix">
			<div class="section">
				<%= image_tag "pic-sapporo.jpg" %>
				<h3>札幌クラス</h3>
				<div class="snsicon">
					<%= link_to image_tag("Facebook.png", width: 40), 'https://www.facebook.com/Capoeiraangolasapporo/',target: ["_blank"] %>
				</div>
				<p>札幌市白石区を拠点に活動しています。専用の道場を構え本格的な雰囲気の中練習ができます。金曜日にはアクセスのよいスタジオでも練習しています。カポエィラ・アンゴラを学ぶ最適な環境です！</p>

			</div>
			<div class="section">
				<%= image_tag "pic-obihiro.jpg" %>
				<h3>帯広クラス</h3>
				<div class="snsicon">
					<%= link_to image_tag("Instagram.png", width: 40), 'https://www.instagram.com/massa_batata/', target: ["_blank"] %>
					<%= link_to image_tag("Twitter.png", width: 40), 'https://twitter.com/obi_capo', target: ["_blank"] %>
				</div>
				<p>帯広市を拠点に活動しています。週に１回の通常練習と、不定期に初心者向け体験会”Vamos Capoeira!”を開催し、カポエイラの技術向上と普及に努めています。</p>
			</div>
		</div>
	</div>
</div>


<!--サイドスペース-->
<div class="sidemenu">
	<h2 class="title">お知らせ</h2>
	<div class="information">
		<h3>Information</h3>
		<hr width="270px" align="left">
	</div>
	<div class="movie">
		<h3>Movie</h3>
		<hr width="270px" align="left">
	</div>
</div>

app/views/home/obihiro.html.erb
<div class="main">
	<h1 class="heading">帯広クラス ―Class Ohihiro－</h1>
	<div class="lesson-info">
		<h2 class="title">帯広クラスについて</h2>
		<div class="li-wrapper">
			<div class="li-image">
				<%= image_tag "pic-obihiro.jpg" %>
			</div>
			<div class="li-description">
				<p>　私たちのクラスは帯広市を拠点に活動しています。週に１回の通常練習と、不定期に初心者向け体験会”Vamos Capoeira!”を開催し、カポエイラの技術向上と普及に努めています。</p>
				　メンバーは男女比半々で、年齢は２０代～３０代で活動しています。新しい趣味としてカポエイラに挑戦したい方、歓迎いたします！
			</div>
		</div>
	</div>

	<div class="lesson-details">
		<h2 class="title">クラス情報</h2>
		<div class="ld-description">
			<p>※練習日時や場所はは急きょ変更になる場合があります。サイドメニューの<a href="https://angolaobihiro.1net.jp/bbs.html">「掲示板」 </a>をご確認ください！</p>
			<p>※練習には上靴、長ズボンＴシャツなど動きやすい服装をご持参ください（半ズボンはご遠慮ください）。見学もＯＫです。お気軽にお越しください！</p>
		</div>

		<div class="ld-class-wrapper">
			<h3 class="subheading">【通常練習】毎週 日 曜日</h3>
			<div class="ld-class-description">
				<p>時間：19:00～21:00</p>
				<p>場所：帯広の森コミュニティセンター</p>
				<p>住所：空港南町南１１線４３番地</p>
			</div>
			<div class="ld-class-map">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2923.6209102768403!2d143.15349231501588!3d42.880844910046676!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5f739baa5799e59d%3A0x3f8b758d53f2d1b9!2z5biv5bqD44Gu5qOu44Kz44Of44Ol44OL44OG44Kj44K744Oz44K_44O8!5e0!3m2!1sja!2sjp!4v1559561711777!5m2!1sja!2sjp" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>

		<div class="ld-class-wrapper">
			<h3 class="subheading">【体験会"Vamos Capoeira!"】 不定期開催</h3>
			<div class="ld-class-description">
				<p>カポエィラを楽しもう！ カポエイラにトライしてみたい方のための、</p>
				<p>未経験者・初心者大歓迎の練習会です。</p>
				<br>
				<p>場所：とかちプラザ 5F フィットネススタジオ</p>
				<p>住所：北海道帯広市西４条南１３丁目1</p>
			</div>
			<div class="ld-class-map">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2921.8961609458343!2d143.19851571501707!3d42.91723090772566!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5f7399419ae5427d%3A0xba49321d5723866f!2z44Go44GL44Gh44OX44Op44K2!5e0!3m2!1sja!2sjp!4v1559563590781!5m2!1sja!2sjp" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>

	</div>
</div>


<!--サイドスペース-->
<div class="sidemenu">
	<h2>掲示板</h2>
	<div class="information">
		練習連絡用の掲示板です！
		<a href="https://angolaobihiro.1net.jp/bbs.html"><img src="images/obihiro/keijiban.jpg"></a>
		<hr width="270px" align="left">
	</div>
</div>
  
  

app/views/home/sapporo.html.erb
<div class="main">
	<h1 class="heading">札幌クラス ―Class Sapporo－</h1>
	<div class="lesson-info">
		<h2 class="title">札幌クラスについて</h2>
		<div class="li-wrapper clearfix">
			<div class="li-image">
				<%= image_tag "pic-sapporo.jpg" %>
			</div>
			<div class="li-description">
				<p>　札幌市白石区を拠点に活動しています。専用の道場を構え本格的な雰囲気の中練習ができます。金曜日にはアクセスのよいスタジオでも練習しています。カポエィラ・アンゴラを学ぶ最適な環境です！</p>
			</div>
		</div>
	</div>


	<div class="lesson-details">
		<h2 class="title">クラス情報</h2>
		<div class="ld-description">
			<p>※練習日時や場所はは急きょ変更になる場合があります。<a href="https://www.facebook.com/Capoeiraangolasapporo/">facebook </a>にてご確認ください！</p>
			<p>※練習には上靴、長ズボンＴシャツなど動きやすい服装をご持参ください（半ズボンはご遠慮ください）。見学もＯＫです。お気軽にお越しください！</p>
		</div>

		<div class="ld-class-wrapper">
			<h3 class="subheading">【通常練習】毎週 月・水・土 曜日</h3>
			<div class="ld-class-description">
				<p>時間：21:00～23:00</p>
				<p>場所：札幌アカデミア</p>
				<p>住所：札幌市白石区川北2327-22</p>
			</div>
			<div class="ld-class-map">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2914.6244505660934!2d141.4314972151847!3d43.070365497940635!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5f0b2c0f7e1bd4b9%3A0xf6fbef1a8329496c!2z44CSMDAzLTA4NTkg5YyX5rW36YGT5pyt5bmM5biC55m955-z5Yy65bed5YyX77yS77yT77yS77yX!5e0!3m2!1sja!2sjp!4v1559566852103!5m2!1sja!2sjp" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>
		
		<div class="ld-class-wrapper">
			<h3 class="subheading">【通常練習】毎週 金 曜日</h3>
			<div class="ld-class-description">
				<p>場所：スタジオ・アマンテ　デル　バイレ</p>
				<p>住所：札幌市白石区南郷通17丁目南6-18</p>
			</div>
			<div class="ld-class-map">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d23330.797810504984!2d141.4065279949833!3d43.03407268455805!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5f0b2b0e51cb2c81%3A0x85efb7f7d125a213!2z44Os44Oz44K_44Or44K544K_44K444Kq44O744Ki44Oe44Oz44OGIOODh-ODqyDjg5DjgqTjg6w!5e0!3m2!1sja!2sjp!4v1559566965306!5m2!1sja!2sjp" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>

	</div>
	
</div>

<!--サイドスペース-->
<div class="sidemenu">
	<h2>facebook</h2>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
	<meta charset="utf-8">
	<title>Capoeira Angola Center Hokkaido</title>
	<%= csrf_meta_tags %>
  <%= csp_meta_tag %>
	<link rel="stylesheet" href="style.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>




<body>
	<div class="wrapper">

		<div class="header clearfix">
			<%= image_tag "logo.jpg", class: "h-logo" %>
			<div class="h-description">
				<h3>Capoeira Angola Center Hokkaido</h3>
				<p>is supervised <b><i>Contramestre Denis</i></b></p>
				<p>Especially thanks for  <b><i>MESTRE JOAO GRANDE!!</i></b></p>
			</div>
		</div>
		<ul class="global-navi">
			<li><%= link_to "TOP", home_index_path %></li>
			<li><%= link_to "Capoeira Angola", home_about_path %></li>
			<li><%= link_to "グループについて", home_group_path  %></li>
			<li><%= link_to "札幌クラス", home_sapporo_path %></li>
			<li><%= link_to "帯広クラス", home_obihiro_path %></li>
			<li><%= link_to "MEMBER", menus_path %></li>
		</ul>

	  	<div class="content clearfix">
	  	  <%= yield %>
	 	</div>
    
	    <div class="footer clearfix">
			<div class="f-description">
				<h3>Capoeira Angola Center Hokkaido</h3>
				<p>カポエイラ・アンゴラ・センター・北海道</p>
			</div>

				

			<div class="f-facebook">
				  <!--<div class="fb-page" data-href="https://www.facebook.com/Capoeiraangolasapporo/" data-tabs="" data-width="" data-height="" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false"><blockquote cite="https://www.facebook.com/Capoeiraangolasapporo/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/Capoeiraangolasapporo/">Capoeira Angola Center Hokkaido -Sapporo -study group</a></blockquote></div>-->
			</div>
		</div>
	 
	 </div>
    
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-wrapper clearfix">
    <div class="field">
      <%= form.label :date %>
      <%= form.date_select :date %>
    </div>
  
    <div class="field">
      <%= form.label :remark %>
      <%= form.text_field :remark %>
    </div>
  
    <div class="field-moviment">
      <%= form.label :movement %>
      <%= form.text_area :movement, size: "30x20" %>
    </div>
  
    <div class="field-music">
      <%= form.label :music %>
      <%= form.text_area :music, size: "30x20" %>
    </div>
  
    <div class="field-image">
      <%= form.label :image %>
      <%= form.text_field :image %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
  
<% end %>

app/views/menus/_menu.html.erb
    <div class="menu clearfix">
      
      <h3 class="menu-remark"><%= link_to menu.remark, menu %>（<%= menu.date %>）</h3>
      <div>
        <%= link_to '編集', edit_menu_path(menu) %>
        <%= link_to '削除', menu, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      
      <div class="menu-contents">
        <h3>Movement</h3>
        <p>　<%= simple_format(menu.movement) %></p>
      </div>
      <div class="menu-contents">
        <h3>Music</h3>
        <p>　<%= simple_format(menu.music) %></p>
      </div>   
      <div class="menu-image">
        <p>　<%= menu.image %></p>
      </div>       
      
    </div>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%#= link_to 'Show', @menu %> |
<%= link_to '戻る', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="heading">My 練習メニュー</h2>

<div class="clearfix">
  <h2 class="title"><%= link_to 'メニューを記録する', new_menu_path %></h2>
  <div class="sort-menu">
    <p>Serch</p>
      <%= form_tag(menus_path, method: :get) do %>
      <%= text_field_tag :search %>
      <%= submit_tag 'Search', :remark => nil %>
    <% end %>
  </div>
</div>


<div class="menues">
  <div>
    <p>Serch：<%= params[:search] %></p>
  </div>

  <% if @menus.empty? %>
    <div class="serch-comment">
      <h3>検索結果がありません！</h3>
    </div>
  <% else %>
    <div class="serch-comment">
      <h3><%= @menus.count %>件のメニュー</h3>
    </div>
    <%= render @menus %>
  <% end %>
</div>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to '戻る', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="menu clearfix">
    
    <h3 class="menu-remark"><%= link_to @menu.remark, @menu %>（<%= @menu.date %>）</h3>
    <div>
      <%= link_to '編集', edit_menu_path(@menu) %>
      <%= link_to '削除', @menu, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    
    <div class="menu-contents">
      <h3>Movement</h3>
      <p>　<%= simple_format(@menu.movement) %></p>
    </div>
    <div class="menu-contents">
      <h3>Music</h3>
      <p>　<%=simple_format(@menu.music) %></p>
    </div>   
    <div class="menu-image">
      <p>　<%= @menu.image %></p>
    </div>
  </div>

  <div class="comments">
    <%= render @menu.comments %>
    <%#= link_to "編集" [:edit, @comment.menu, @comment] %>
    <%#= link_to "削除" [@comment.menu, @comment], method: :delete, data: {confirm: "Are you sure?"} %>  
  </div>

  <div class="comment-form">
    <%= render 'comments/form' %>
  </div>






<%= link_to '戻る', menus_path %>